### ISSUE TITLE
如何修改裁剪的代码

### ISSUE THREAD

**Issue by xiaosheng1126** [xingda920813/HelloCamera2#1]
你好，我认真看了，修改布局里面52和896裁剪的就不全，我没看到裁剪的代码啊！能指点一下吗

**Comment by xingda920813** [comment]
裁剪的代码在 android.graphics.Bitmap com.xdandroid.hellocamera2.util.BitmapUtils.crop(android.graphics.Bitmap originalBitmap) 方法中，修改了布局 XML 中的尺寸后，还需要修改 crop 方法内使用的尺寸参数。

crop 方法涉及尺寸的部分代码如下（com.xdandroid.hellocamera2.util.BitmapUtils 的第 40 - 45 行）:

//在1280x720的设计图上，裁剪起点坐标(52, 80)
int x = (int) (52 * scaleX + 0.5);
int y = (int) (80 * scaleY + 0.5);
//在1280x720的设计图上，裁剪区域大小为896x588
int width = (int) (896 * scaleX + 0.5);
int height = (int) (588 * scaleY + 0.5);

需要根据布局 XML 中修改过的尺寸，修改这里的起点坐标和裁剪区域大小（相对于 1280x720 的设计图）。

**Comment by xingda920813** [comment]
裁剪的代码在 android.graphics.Bitmap com.xdandroid.hellocamera2.util.BitmapUtils.crop(android.graphics.Bitmap originalBitmap) 方法中，修改了布局 XML 中的尺寸后，还需要修改 crop 方法内使用的尺寸参数。

crop 方法涉及尺寸的部分代码如下（com.xdandroid.hellocamera2.util.BitmapUtils 的第 40 - 45 行）:

//在1280x720的设计图上，裁剪起点坐标(52, 80)
int x = (int) (52 \* scaleX + 0.5);
int y = (int) (80 \* scaleY + 0.5);
//在1280x720的设计图上，裁剪区域大小为896x588
int width = (int) (896 \* scaleX + 0.5);
int height = (int) (588 \* scaleY + 0.5);

需要根据布局 XML 中修改过的尺寸，修改这里的起点坐标和裁剪区域大小（相对于 1280x720 的设计图）。

**Comment by xiaosheng1126** [comment]
非常感谢看到了，我昨天一直在相机界面找，然后看到了压缩图片，没太注意看到裁剪！
能交个朋友吗？以后没事还可以探讨一下开发！我的qq:785928147
