### ISSUE TITLE
Is there any option to resize the preview dyanamically

### ISSUE THREAD

**Issue by rahulbm** [xingda920813/HelloCamera2#10]
The HelloCamera2 it is really good. I am looking for resizing the preview during Camera on. Is there any option could you please help me

**Comment by hemanth2k13** [comment]
Hi I'm new to android development, I usually add libraries to my project in dependencies using compile or implementation. Or .jar file. I couldn't find in documentation on how to add this library to my project. Please help. Thank you.

**Comment by hemanth2k13** [comment]
Hi I'm new to android development, I usually add libraries to my project in dependencies using compile or implementation. Or .jar file. I couldn't find in documentation on how to add this library to my project. Please help. Thank you.
