### ISSUE TITLE
自定义相机可以是竖屏的吗

### ISSUE THREAD

**Issue by BTFTUK** [xingda920813/HelloCamera2#2]

**Comment by xingda920813** [comment]
目前的版本只支持横屏，因为涉及到裁剪坐标的计算和导航栏的因素，同时支持竖屏有困难，修改的地方会非常多。

但我的 Camera2Activity 借鉴的 googlesamples / android-Camera2Basic，是支持竖屏的，可以参考它的 Camera2BasicFragment，稍作改动，应该是一个简易能用的竖屏相机。

项目地址：https://github.com/googlesamples/android-Camera2Basic

Camera2BasicFragment：https://github.com/googlesamples/android-Camera2Basic/blob/master/Application/src/main/java/com/example/android/camera2basic/Camera2BasicFragment.java

**Comment by BTFTUK** [comment]
@xingda920813 好的谢谢
