### ISSUE TITLE
How to tutorial change size camera?

### ISSUE THREAD

**Issue by tunv11** [xingda920813/HelloCamera2#3]
thanks you

**Comment by xingda920813** [comment]
The code for cropping is at android.graphics.Bitmap com.xdandroid.hellocamera2.util.BitmapUtils.crop(android.graphics.Bitmap originalBitmap) method. After you change sizes in layout XML, you also need to modify size parameters used in the cropping method.

The crop size processing code in the cropping method shows below (com.xdandroid.hellocamera2.util.BitmapUtils, Line 40 - 45): 

//The crop starts from coord (52, 80), when in 1280x720 design spec.
int x = (int) (52 * scaleX + 0.5);
int y = (int) (80 * scaleY + 0.5);
//The crop size is 896(px) x 588(px), when in 1280x720 design spec.
int width = (int) (896 * scaleX + 0.5);
int height = (int) (588 * scaleY + 0.5);

You need to modify the 2 parameters above, according to the sizes modified in layout XML.

**Comment by tunv11** [comment]
thanks you!
