### ISSUE TITLE
您好  您的布局写的有点看不懂

### ISSUE THREAD

**Issue by superzhangbao** [xingda920813/HelloCamera2#4]
请问您的布局写的效果出来跟我copy你的显示出来不一样，我的就是竖屏的效果，而你的变成横屏的效果。还有我的相机预览效果就是不正常的，被旋转放大了

**Comment by xingda920813** [comment]
检查一下你的 AndroidManifest.xml, 尤其是关于屏幕方向的部分.(android:screenOrientation="landscape")
