### ISSUE TITLE
Camera2 的ImageSaver每次会被执行2次，

### ISSUE THREAD

**Issue by Mexicande** [xingda920813/HelloCamera2#5]
昨天在使用你的demo的同时发现，注意到Camera2 的ImageSaver每次会被执行2次
08-02 23:44:53.178 32381-19612/com.xdandroid.hellocamera2 D/Camera2BasicFragment: /data/user/0/com.xdandroid.hellocamera2/cache/images/mFile
08-02 23:44:53.213 32381-19612/com.xdandroid.hellocamera2 D/Camera2BasicFragment: /data/user/0/com.xdandroid.hellocamera2/cache/images/mFile
08-02 23:44:53.235 32381-19612/com.xdandroid.hellocamera2 I/执行ImageSaver: file:///data/user/0/com.xdandroid.hellocamera2/cache/images/mFile
08-02 23:44:53.283 32381-19612/com.xdandroid.hellocamera2 I/执行ImageSaver: file:///data/user/0/com.xdandroid.hellocamera2/cache/images/mFile

**Comment by xingda920813** [comment]
我这边并不会. 机型, 系统版本?

**Comment by Mexicande** [comment]
8.0   google pixel

**Comment by xingda920813** [comment]
无解.
