### ISSUE TITLE
找屏幕最大尺寸的依据是什么呢？

### ISSUE THREAD

**Issue by dukezhao** [xingda920813/HelloCamera2#8]
算法好像不太明白，请指教，google源码的有什么缺陷？

**Comment by xingda920813** [comment]
这是项目的一个需求, 保证上传的图片不会过大, Google 直接使用最大像素, 图片大小会上 M, 给上传和服务端存储带来麻烦. 你也可以直接使用 Google 的.

**Comment by dukezhao** [comment]
多谢，我研究一下！
