### ISSUE TITLE
相机权限问题

### ISSUE THREAD

**Issue by superzhangbao** [xingda920813/HelloCamera2#9]
作者你好，为什么你的项目在6.0以下的手机上也会弹出Camera申请权限的弹窗，而且点禁止的话，会报空指针。错误如下：
java.lang.NullPointerException: onNext called with null. Null values are generally not allowed in 2.x operators and sources.

出错的代码位置：initCamera()内；
Flowable.create((FlowableOnSubscribe<Camera>) e -> e.onNext(CameraUtils.getCamera()),BackpressureStrategy.BUFFER)**********************这里
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(camera -> {
                });
我项目利用的是rxPermissions做的权限管理，在6.0以下相机权限是默认为true，等到打开相机的activity就会弹出申请相机权限的弹窗。不知道是为什么？
请问该如何解决，谢谢！

**Comment by xingda920813** [comment]
某些设备厂商在 Android 6.0 以下的 ROM 里也做了权限管理的功能（6.0 以下 Google 还没有引入运行时权限机制，是厂商自己做的），有些实现方式是通过拦截 API 实现的，即等到你真正开始使用这个权限的时候，比如 Camera.open() 的时候，再弹框询问用户。在这之前，用 PackageManager 查询是否已授权，始终返回的是 true。所以会在打开 CameraActivity 之后，再弹出框，这个框是手机系统的弹框，之前的权限检查是无效的，这是这些 ROM 比较坑的一个地方。

至于 Crash 问题，刚才已经解决了，现在 camera != null -> onNext(camera), camera == null -> onError(t).
